UPDATE ITEM SET Delay = 125,Range = 20 WHERE Kind = 110
GO

UPDATE K_MONSTER SET iMagic1 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic1) = 0 AND iMagic1 != 0
UPDATE K_MONSTER SET iMagic2 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic2) = 0 AND iMagic2 != 0
UPDATE K_MONSTER SET iMagic3 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic3) = 0 AND iMagic3 != 0
UPDATE K_NPC SET iMagic1 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic1) = 0 AND iMagic1 != 0
UPDATE K_NPC SET iMagic2 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic2) = 0 AND iMagic2 != 0
UPDATE K_NPC SET iMagic3 = 0 WHERE (SELECT COUNT(MagicNum) FROM MAGIC WHERE MagicNum = iMagic3) = 0 AND iMagic3 != 0
GO